### ISSUE TITLE
No existe una forma para obtener las preguntas y respuestas de una votación

### ISSUE THREAD

**Issue by yamikadesu** [EGC-G2-Trabajo-1718/AdministracionVotaciones#1]
Prioridad: Urgente
Descripción: No hay una descripción detallada de cómo obtener las preguntas y respuestas de una votación en la API de administración de votaciones.

**Comment by martos93** [comment]
Se crea en la wiki la descripción de como obtener, crear, editar y eliminar preguntas y respuestas en la API de administración de votaciones.
