### ISSUE TITLE
Realización de Convertidores y Repositorio de Pregunta

### ISSUE THREAD

**Issue by martos93** [EGC-G2-Trabajo-1718/AdministracionVotaciones#12]
Prioridad: Alta.

Descripción: Deben crearse las clases pertinentes de convertidores y el repositorio para la entidad Pregunta.

**Comment by PabloTinoco** [comment]
Ya estarían todos los elementos, una vez validados unimos mi rama con development y cerramos esta issue.

**Comment by PabloTinoco** [comment]
Ya han sido implementadas todas las clases requeridas en esta incidencia y testeadas.
