### ISSUE TITLE
Realización de Convertidores y Repositorio de Respuesta

### ISSUE THREAD

**Issue by martos93** [EGC-G2-Trabajo-1718/AdministracionVotaciones#13]
Prioridad: Alta.
Estado: En curso.
Descripción: Deben crearse las clases pertinentes de convertidores y el repositorio para la entidad Respuesta.

**Comment by franciscoferang** [comment]
Se han creado en el paquete converters las clases RespuestaToStringConverter.java y StringToRespuestaConverter.java y en el paquete repositories se ha creado la interfaz RespuestaRepository.java, procedo a cerrar la issue previa aceptación del coordinador
