### ISSUE TITLE
Realización de servicios

### ISSUE THREAD

**Issue by martos93** [EGC-G2-Trabajo-1718/AdministracionVotaciones#15]
Prioridad: Alta.
Estado: En curso.
Descripción: Deben crearse los servicios de Pregunta, Respuesta, Votación con los metodos básicos (save, delete, list).

**Comment by gontragar** [comment]
Los servicios requeridos han sido creados. Procedo a cerrar la issue previa inspección del Coordinador @PabloTinoco .
