### ISSUE TITLE
Clases Test

### ISSUE THREAD

**Issue by PabloTinoco** [EGC-G2-Trabajo-1718/AdministracionVotaciones#17]
Prioridad: Alta

Se precisa clases Test que se usarán para hacer las pruebas. Dichas clases se implementaran con la libreria JUnit y serán integradas con la herramienta Maven de Eclipse.

**Comment by martos93** [comment]
Se ha detectado que con los cambios de ID del populate, los test no funcionan correctamente. Se procede a cambiar las id que referencian las clases en los test para subsanar este error.
