### ISSUE TITLE
Error 404 en cualquier URL del subsistema

### ISSUE THREAD

**Issue by robgc** [EGC-G2-Trabajo-1718/AdministracionVotaciones#18]
Prioridad: Alta

La aplicación presenta fallos de configuración respecto a las URLs. Después de probar en un entorno con la base de datos poblada adecuadamente, Apache Tomcat extrae los contenidos del fichero .war generado por la construcción del código correctamente, sin embargo para cualquier URL definida en el fichero de configuración de Spring solo se obtienen errores 404.

Para comprobar si no era fallo en la configuración de los contenedores, se ha intentado desplegar un proyecto de la asignatura de Diseño y Pruebas consiguiendo resultados positivos, siguiendo exactamente los mismos pasos en el despliegue.

**Comment by martos93** [comment]
¿Podria especificar las url que se han probado para intentar reproducir los fallos en nuestro local?

**Comment by martos93** [comment]
Se detectó un problema en la configuración de la base de datos de nuestro proyecto que hacia que apuntara a "localhost" en lugar de la base de datos proporcionada por integración. Dado que no recibimos respuesta ni issues nuevas al respecto damos la incidencia por cerrada.
