### ISSUE TITLE
Error de build en la rama development

### ISSUE THREAD

**Issue by franciscoferang** [EGC-G2-Trabajo-1718/AdministracionVotaciones#19]
Prioridad: Urgente

En la modificación de la rama development en el commit fix: reparacion de rama (ffc7f811a1878c492f1f8275d8e7d2bc3c7c3871) he comprobado que no funciona el build del proyecto.

Es necesario la participación de todos los participantes para subsanar este error lo antes posible.

Para reproducir el error Run as > Maven install

**Comment by martos93** [comment]
Se han realizado los cambios pertinentes en la configuración de travis para que se realice correctamente el build. Se da por cerrada la issue.
