### ISSUE TITLE
Mejorar la sección "Tecnología usada" en la wiki

### ISSUE THREAD

**Issue by robgc** [EGC-G2-Trabajo-1718/AdministracionVotaciones#2]
Prioridad: Alta

- No se especifica la versión de Java necesaria.
- Por el momento parece que se está empleando Maven como sistema de gestión de bibliotecas.
- Spring no es una biblioteca, es un framework. Spring permite crear APIs REST, tiene paquetes de Maven (bibliotecas) disponibles para ello. Hay guías en varias webs sobre ello.
- El pom.xml actual puede incluir dependencias innecesarias para el despliegue de vuestro proyecto.

**Comment by PabloTinoco** [comment]
@robgc  Podría especificar con mayor detalle las dependencias que podrían ser innecesarios dentro de nuestro pom.xml. Al margen de eso, las demas peticiones han sido resueltas.

**Comment by robgc** [comment]
Hay muchas dependencias como Spring o Apache Tiles que no son necesarias. Puesto que vais a construir una API, no una aplicación web. Estudiad qué dependencias son realmente necesarias para que Jackson funcione.

**Comment by PabloTinoco** [comment]
@robgc Se han quitado todas las dependencias posibles para poder compilar nuestra Sistema. Diganos si cumple los requerimientos y de no ser así cual modificar.
Dejo la incidencia abierta hasta que haya sido validado por el equipo de Integración.
