### ISSUE TITLE
Necesidad nueva funcionalidad API: obtención listado votaciones

### ISSUE THREAD

**Issue by jesusrivasjmnez** [EGC-G2-Trabajo-1718/AdministracionVotaciones#21]
Prioridad: media

Desde el equipo de Arquitectura/Integracion requerimos de una nueva funcionalidad de la API para usar en el portal de votaciones. Esta funcionalidad debe devolver un listado de todas las votaciones.

**Comment by PabloTinoco** [comment]
Actualmente estamos inmersos en el proceso de Integración, así como en la preparación del Milestone 4.

Sentimos no poder atender la indicencia en este momento, vamos a pasar la prioridad a media.

**Comment by PabloTinoco** [comment]
@jesusrivasjmnez ya esta implementada la funcionalidad requerida.
