### ISSUE TITLE
Obtención de la clave de cifrado de la votación

### ISSUE THREAD

**Issue by NachoAlesLopez** [EGC-G2-Trabajo-1718/AdministracionVotaciones#3]
Prioridad: media
Descripción: Cabina de votación necesita que aportes la clave que se usará para cifrar el voto. Es recomendado que la clave tenga como codificación UTF-8 ya que el cifrado requiere una transformación del voto de UTF-8 a Base64 y cifrar el resultado de esa operación.

**Comment by PabloTinoco** [comment]
Vamos a crear un nuevo campo "cifrado", que será generado al crear la votación. Este valor podrá obtenerlo con la consulta a Votación. 
Cuando se modifique nuestra wiki con el nuevo requerimiento será notificado.

**Comment by martos93** [comment]
Como se ha comentado, hemos creado el campo Clave en la tabla de votación.
