### ISSUE TITLE
Creación plantillas Jinja2

### ISSUE THREAD

**Issue by PabloTinoco** [EGC-G2-Trabajo-1718/AdministracionVotaciones#4]
Prioridad: Urgente

Se precisa la creación de plantillas HTML con la herramienta JINJA2 para la vista "Crear votación". Dichas plantillas se podrán ver en la wiki para que otros subsistemas (Visualización) puedan tener acceso a ellas.

**Comment by gontragar** [comment]
La plantilla de creación de votación ha sido creada y subida a la Wiki de la asignatura.
https://1984.lsi.us.es/wiki-egc/index.php/Administraci%C3%B3n_de_votaciones_-_17_18_-_G2#Template_Creaci.C3.B3n
@robgc

**Comment by PabloTinoco** [comment]
Dejamos la incidencia abierta por si se requieran nuevas vistas para nuestro subsistema.

**Comment by PabloTinoco** [comment]
Ya que hasta la fecha no se nos ha requerido nuevas plantillas queda cerrada esta issue.
