### ISSUE TITLE
Se necesita una forma de obtener las preguntas pasando la id de la votación

### ISSUE THREAD

**Issue by yamikadesu** [EGC-G2-Trabajo-1718/AdministracionVotaciones#5]
Prioridad: Urgente
Descripción: Falta describir en la API una forma de obtener las preguntas de una votación dada (pasando el id de la votación) y lo mismo para las respuestas (pasando el id de la pregunta)

**Comment by martos93** [comment]
Se ha creado en la wiki de la asignatura una API para ambos casos.
