### ISSUE TITLE
Programación funciones API

### ISSUE THREAD

**Issue by PabloTinoco** [EGC-G2-Trabajo-1718/AdministracionVotaciones#7]
Prioridad: Alta

Necesitamos programar las funciones que se encargarán de crear los JSON que precisarán otros subsistemas.
Se necesita las API de Votación, Pregunta y Respuesta.

**Comment by martos93** [comment]
Se han subido los archivos de la API de votación.

**Comment by PabloTinoco** [comment]
Se ha decidido que han sido creadas todas las funcionalidades API necesarias para el sistema, lsitadas en los commits de esta issue. De ser necesaria alguna nueva se creará una nueva issue.
